name: run program

on:
  repository_dispatch:
    types: [ test ]

  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "23 0 * * *" # 2:23am every day israel time (23:23 UTC time)

permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    services:
      elasticsearch:
        image: ghcr.io/tal-sitton/seret-search:latest
        ports:
          - 9200:9200
        options: >-
          --name elasticsearch

    steps:

      - uses: actions/checkout@v4
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/checkout@v4
        if: github.event_name != 'pull_request'

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run program
        run:
          python main.py
        env:
          ELASTIC_HOST: http://localhost:9200

      - name: config git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: add elastic-data
        run: |
          sudo rm -rf esdata
          docker stop elasticsearch
          docker cp elasticsearch:/usr/share/elasticsearch/data esdata
          find esdata -type f -name '*.lock' -delete
          zip -r esdata.zip esdata
          git add esdata.zip

      - name: commit file and push
        run: |
          git commit -m "Update elastic-data"
          git push

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push Docker image
        run: |
          docker commit elasticsearch ghcr.io/tal-sitton/seret-search:latest
          docker push ghcr.io/tal-sitton/seret-search:latest
